//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.Sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public long Id { get; set; }
        public string Text { get; set; }
        public long PermissionTypeId { get; set; }
        public int OrderNumer { get; set; }
        public byte IfDel { get; set; }
        public byte IfValid { get; set; }
    
        public virtual PermissionType PermissionType { get; set; }
    }
}
