// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4Demo.继承模式_基方法中的片段
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\Workplace\CSharpExample\CSharpExample\CSharpBasic\T4Demo\继承模式：基方法中的片段\MyTextTemplate1.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class MyTextTemplate1 : SharedFragments
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("begin 1\r\n   ");
            
            #line 3 "E:\Workplace\CSharpExample\CSharpExample\CSharpBasic\T4Demo\继承模式：基方法中的片段\MyTextTemplate1.tt"
 SharedText(2); 
            
            #line default
            #line hidden
            this.Write("end 1\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
