// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 15.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace T4Demo.继承模式_基体中的文本
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\git\Programming-in-CSharp\CSharpExample\CSharpBasic\T4Demo\继承模式：基体中的文本\DerivedTemplate1.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class DerivedTemplate1 : AbstractBaseTemplate1
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 2 "D:\git\Programming-in-CSharp\CSharpExample\CSharpBasic\T4Demo\继承模式：基体中的文本\DerivedTemplate1.tt"
 
  // Set the base template properties:
  base.Description = "Description for this derived class"; 

  // Run the base template:
  base.TransformText();



            
            #line default
            #line hidden
            this.Write("End material for DerivedTemplate1.\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 13 "D:\git\Programming-in-CSharp\CSharpExample\CSharpBasic\T4Demo\继承模式：基体中的文本\DerivedTemplate1.tt"

// Provide a fragment specific to this derived template:

protected override void SpecificFragment(int n)
{

        
        #line default
        #line hidden
        
        #line 18 "D:\git\Programming-in-CSharp\CSharpExample\CSharpBasic\T4Demo\继承模式：基体中的文本\DerivedTemplate1.tt"
this.Write("   Specific to DerivedTemplate1 : ");

        
        #line default
        #line hidden
        
        #line 19 "D:\git\Programming-in-CSharp\CSharpExample\CSharpBasic\T4Demo\继承模式：基体中的文本\DerivedTemplate1.tt"
this.Write(this.ToStringHelper.ToStringWithCulture(n));

        
        #line default
        #line hidden
        
        #line 19 "D:\git\Programming-in-CSharp\CSharpExample\CSharpBasic\T4Demo\继承模式：基体中的文本\DerivedTemplate1.tt"
this.Write("\r\n");

        
        #line default
        #line hidden
        
        #line 20 "D:\git\Programming-in-CSharp\CSharpExample\CSharpBasic\T4Demo\继承模式：基体中的文本\DerivedTemplate1.tt"

}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
