//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XMLDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE root [
        ///  &lt;!ELEMENT root ANY&gt;
        ///  &lt;!ELEMENT Person ANY&gt;
        ///  &lt;!ELEMENT Customer EMPTY&gt;
        ///  &lt;!ELEMENT Team EMPTY&gt;
        ///  &lt;!ATTLIST Person SSN ID #REQUIRED&gt;
        ///  &lt;!ATTLIST Customer id IDREF #REQUIRED&gt;
        ///  &lt;!ATTLIST Team members IDREFS #REQUIRED&gt;
        ///]&gt;
        ///&lt;root&gt;
        ///  &lt;Person SSN=&apos;A111&apos; Name=&apos;Fred&apos; /&gt;
        ///  &lt;Person SSN=&apos;A111&apos; /&gt;
        ///  &lt;Person SSN=&apos;A222&apos; Name=&apos;Tom&apos; /&gt;
        ///  &lt;Customer id=&apos;A111&apos; /&gt;
        ///  &lt;Customer id=&apos;A222334444&apos; /&gt;
        ///  &lt;Team members=&apos;A222334444 A333445555&apos; /&gt;
        ///&lt;/root&gt; 的本地化字符串。
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Order&gt;
        ///  &lt;CustomerName&gt;洪磊&lt;/CustomerName&gt;
        ///  &lt;CustomerNumber&gt;HLK20130728&lt;/CustomerNumber&gt;
        ///  &lt;Items&gt;
        ///    &lt;OrderItem Name=&quot;电脑&quot; Count=&quot;20&quot; /&gt;
        ///    &lt;OrderItem Name=&quot;电话&quot; Count=&quot;10&quot; Brand=&quot;SONY&quot; /&gt;
        ///  &lt;/Items&gt;
        ///&lt;/Order&gt; 的本地化字符串。
        /// </summary>
        internal static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
    }
}
