//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lxrenb
    {
        public int lxrenbh { get; set; }
        public string xm { get; set; }
        public Nullable<byte> lbdm { get; set; }
        public string sjhm { get; set; }
        public string qq { get; set; }
        public string xmsx { get; set; }
    }
}
